/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservasiRouteImport } from './routes/reservasi'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ProfilDokterRouteImport } from './routes/profil-dokter'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as ErrorPageRouteImport } from './routes/error-page'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as Login_layoutRouteImport } from './routes/login/__layout'

const ReservasiRoute = ReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDokterRoute = ProfilDokterRouteImport.update({
  id: '/profil-dokter',
  path: '/profil-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorPageRoute = ErrorPageRouteImport.update({
  id: '/error-page',
  path: '/error-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const Login_layoutRoute = Login_layoutRouteImport.update({
  id: '/login/__layout',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/login': typeof Login_layoutRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/login/__layout': typeof Login_layoutRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/login'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/login/__layout'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRoute
  ErrorPageRoute: typeof ErrorPageRoute
  LayananRoute: typeof LayananRoute
  NotFoundRoute: typeof NotFoundRoute
  ProfilDokterRoute: typeof ProfilDokterRoute
  PromoRoute: typeof PromoRoute
  ReservasiRoute: typeof ReservasiRoute
  Login_layoutRoute: typeof Login_layoutRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservasi': {
      id: '/reservasi'
      path: '/reservasi'
      fullPath: '/reservasi'
      preLoaderRoute: typeof ReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-dokter': {
      id: '/profil-dokter'
      path: '/profil-dokter'
      fullPath: '/profil-dokter'
      preLoaderRoute: typeof ProfilDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-page': {
      id: '/error-page'
      path: '/error-page'
      fullPath: '/error-page'
      preLoaderRoute: typeof ErrorPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/__layout': {
      id: '/login/__layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Login_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRoute,
  ErrorPageRoute: ErrorPageRoute,
  LayananRoute: LayananRoute,
  NotFoundRoute: NotFoundRoute,
  ProfilDokterRoute: ProfilDokterRoute,
  PromoRoute: PromoRoute,
  ReservasiRoute: ReservasiRoute,
  Login_layoutRoute: Login_layoutRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
