/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservasiRouteImport } from './routes/reservasi'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ProfilDokterRouteImport } from './routes/profil-dokter'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as ErrorPageRouteImport } from './routes/error-page'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTestimoniRouteImport } from './routes/admin/testimoni'
import { Route as AdminReservasiRouteImport } from './routes/admin/reservasi'
import { Route as AdminPromoRouteImport } from './routes/admin/promo'
import { Route as AdminProfilDokterRouteImport } from './routes/admin/profil-dokter'
import { Route as AdminLayananRouteImport } from './routes/admin/layanan'
import { Route as AdminGaleriRouteImport } from './routes/admin/galeri'
import { Route as AdminFaqRouteImport } from './routes/admin/faq'
import { Route as AdminArtikelRouteImport } from './routes/admin/artikel'
import { Route as AdminDataPasienIndexRouteImport } from './routes/admin/data-pasien/index'
import { Route as AdminDataPasienRontgenRouteImport } from './routes/admin/data-pasien/rontgen'

const ReservasiRoute = ReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDokterRoute = ProfilDokterRouteImport.update({
  id: '/profil-dokter',
  path: '/profil-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorPageRoute = ErrorPageRouteImport.update({
  id: '/error-page',
  path: '/error-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimoniRoute = AdminTestimoniRouteImport.update({
  id: '/admin/testimoni',
  path: '/admin/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasiRoute = AdminReservasiRouteImport.update({
  id: '/admin/reservasi',
  path: '/admin/reservasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/admin/promo',
  path: '/admin/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfilDokterRoute = AdminProfilDokterRouteImport.update({
  id: '/admin/profil-dokter',
  path: '/admin/profil-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayananRoute = AdminLayananRouteImport.update({
  id: '/admin/layanan',
  path: '/admin/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGaleriRoute = AdminGaleriRouteImport.update({
  id: '/admin/galeri',
  path: '/admin/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/admin/artikel',
  path: '/admin/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataPasienIndexRoute = AdminDataPasienIndexRouteImport.update({
  id: '/admin/data-pasien/',
  path: '/admin/data-pasien/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataPasienRontgenRoute = AdminDataPasienRontgenRouteImport.update({
  id: '/admin/data-pasien/rontgen',
  path: '/admin/data-pasien/rontgen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profil-dokter': typeof AdminProfilDokterRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/reservasi': typeof AdminReservasiRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/data-pasien/rontgen': typeof AdminDataPasienRontgenRoute
  '/admin/data-pasien/': typeof AdminDataPasienIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profil-dokter': typeof AdminProfilDokterRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/reservasi': typeof AdminReservasiRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin/data-pasien/rontgen': typeof AdminDataPasienRontgenRoute
  '/admin/data-pasien': typeof AdminDataPasienIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/error-page': typeof ErrorPageRoute
  '/layanan': typeof LayananRoute
  '/not-found': typeof NotFoundRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/profil-dokter': typeof AdminProfilDokterRoute
  '/admin/promo': typeof AdminPromoRoute
  '/admin/reservasi': typeof AdminReservasiRoute
  '/admin/testimoni': typeof AdminTestimoniRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/admin/data-pasien/rontgen': typeof AdminDataPasienRontgenRoute
  '/admin/data-pasien/': typeof AdminDataPasienIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/admin/artikel'
    | '/admin/faq'
    | '/admin/galeri'
    | '/admin/layanan'
    | '/admin/profil-dokter'
    | '/admin/promo'
    | '/admin/reservasi'
    | '/admin/testimoni'
    | '/admin/'
    | '/login/'
    | '/admin/data-pasien/rontgen'
    | '/admin/data-pasien/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/admin/artikel'
    | '/admin/faq'
    | '/admin/galeri'
    | '/admin/layanan'
    | '/admin/profil-dokter'
    | '/admin/promo'
    | '/admin/reservasi'
    | '/admin/testimoni'
    | '/admin'
    | '/login'
    | '/admin/data-pasien/rontgen'
    | '/admin/data-pasien'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/error-page'
    | '/layanan'
    | '/not-found'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi'
    | '/admin/artikel'
    | '/admin/faq'
    | '/admin/galeri'
    | '/admin/layanan'
    | '/admin/profil-dokter'
    | '/admin/promo'
    | '/admin/reservasi'
    | '/admin/testimoni'
    | '/admin/'
    | '/login/'
    | '/admin/data-pasien/rontgen'
    | '/admin/data-pasien/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRoute
  ErrorPageRoute: typeof ErrorPageRoute
  LayananRoute: typeof LayananRoute
  NotFoundRoute: typeof NotFoundRoute
  ProfilDokterRoute: typeof ProfilDokterRoute
  PromoRoute: typeof PromoRoute
  ReservasiRoute: typeof ReservasiRoute
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminGaleriRoute: typeof AdminGaleriRoute
  AdminLayananRoute: typeof AdminLayananRoute
  AdminProfilDokterRoute: typeof AdminProfilDokterRoute
  AdminPromoRoute: typeof AdminPromoRoute
  AdminReservasiRoute: typeof AdminReservasiRoute
  AdminTestimoniRoute: typeof AdminTestimoniRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  AdminDataPasienRontgenRoute: typeof AdminDataPasienRontgenRoute
  AdminDataPasienIndexRoute: typeof AdminDataPasienIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservasi': {
      id: '/reservasi'
      path: '/reservasi'
      fullPath: '/reservasi'
      preLoaderRoute: typeof ReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-dokter': {
      id: '/profil-dokter'
      path: '/profil-dokter'
      fullPath: '/profil-dokter'
      preLoaderRoute: typeof ProfilDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-page': {
      id: '/error-page'
      path: '/error-page'
      fullPath: '/error-page'
      preLoaderRoute: typeof ErrorPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimoni': {
      id: '/admin/testimoni'
      path: '/admin/testimoni'
      fullPath: '/admin/testimoni'
      preLoaderRoute: typeof AdminTestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservasi': {
      id: '/admin/reservasi'
      path: '/admin/reservasi'
      fullPath: '/admin/reservasi'
      preLoaderRoute: typeof AdminReservasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/admin/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profil-dokter': {
      id: '/admin/profil-dokter'
      path: '/admin/profil-dokter'
      fullPath: '/admin/profil-dokter'
      preLoaderRoute: typeof AdminProfilDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/layanan': {
      id: '/admin/layanan'
      path: '/admin/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof AdminLayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/galeri': {
      id: '/admin/galeri'
      path: '/admin/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AdminGaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/admin/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-pasien/': {
      id: '/admin/data-pasien/'
      path: '/admin/data-pasien'
      fullPath: '/admin/data-pasien/'
      preLoaderRoute: typeof AdminDataPasienIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-pasien/rontgen': {
      id: '/admin/data-pasien/rontgen'
      path: '/admin/data-pasien/rontgen'
      fullPath: '/admin/data-pasien/rontgen'
      preLoaderRoute: typeof AdminDataPasienRontgenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRoute,
  ErrorPageRoute: ErrorPageRoute,
  LayananRoute: LayananRoute,
  NotFoundRoute: NotFoundRoute,
  ProfilDokterRoute: ProfilDokterRoute,
  PromoRoute: PromoRoute,
  ReservasiRoute: ReservasiRoute,
  AdminArtikelRoute: AdminArtikelRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminGaleriRoute: AdminGaleriRoute,
  AdminLayananRoute: AdminLayananRoute,
  AdminProfilDokterRoute: AdminProfilDokterRoute,
  AdminPromoRoute: AdminPromoRoute,
  AdminReservasiRoute: AdminReservasiRoute,
  AdminTestimoniRoute: AdminTestimoniRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  AdminDataPasienRontgenRoute: AdminDataPasienRontgenRoute,
  AdminDataPasienIndexRoute: AdminDataPasienIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
