/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ProfilDokterRouteImport } from './routes/profil-dokter'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservasiIndexRouteImport } from './routes/reservasi/index'

const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilDokterRoute = ProfilDokterRouteImport.update({
  id: '/profil-dokter',
  path: '/profil-dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasiIndexRoute = ReservasiIndexRouteImport.update({
  id: '/reservasi/',
  path: '/reservasi/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/layanan': typeof LayananRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi/': typeof ReservasiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/layanan': typeof LayananRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi': typeof ReservasiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/layanan': typeof LayananRoute
  '/profil-dokter': typeof ProfilDokterRoute
  '/promo': typeof PromoRoute
  '/reservasi/': typeof ReservasiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/layanan'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artikel' | '/layanan' | '/profil-dokter' | '/promo' | '/reservasi'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/layanan'
    | '/profil-dokter'
    | '/promo'
    | '/reservasi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRoute
  LayananRoute: typeof LayananRoute
  ProfilDokterRoute: typeof ProfilDokterRoute
  PromoRoute: typeof PromoRoute
  ReservasiIndexRoute: typeof ReservasiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil-dokter': {
      id: '/profil-dokter'
      path: '/profil-dokter'
      fullPath: '/profil-dokter'
      preLoaderRoute: typeof ProfilDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservasi/': {
      id: '/reservasi/'
      path: '/reservasi'
      fullPath: '/reservasi/'
      preLoaderRoute: typeof ReservasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRoute,
  LayananRoute: LayananRoute,
  ProfilDokterRoute: ProfilDokterRoute,
  PromoRoute: PromoRoute,
  ReservasiIndexRoute: ReservasiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
